kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker-deploy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
        app: kafka
        id: "0"
  template:
    metadata:
      labels:
        app: kafka
        id: "0"
    spec:
      containers:
      - name: kafka
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 9092
        - containerPort: 29093
        volumeMounts:
        - mountPath: /prometheus
          name: prometheus-metrics
        env:
        - name: KAFKA_LISTENERS
          value: INTERNAL://:9092, mec://:29093
        - name: KAFKA_ADVERTISED_LISTENERS
          value: INTERNAL://kafka-broker2:9092, mec://192.168.15.187:29093
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: INTERNAL:PLAINTEXT, mec:PLAINTEXT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: INTERNAL 
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_CREATE_TOPICS
          value: upsampling:4:1, f-extraction:4:1, ml:1:1
        - name: EXTRA_ARGS
          value: -javaagent:/prometheus/jmx_prometheus_javaagent-0.15.0.jar=1234:/prometheus/kafka-broker.yml
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: prometheus-metrics
        hostPath:
          path: /home/ubuntu/v3-cognitive-iot/prometheus-metrics-for-kafka/
          type: Directory

