apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pushgateway
    release: prometheus-bind5g-vicomtech
  name: pushgateway-deploy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pushgateway
  template:
    metadata:
      labels:
        app: pushgateway
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: pushgateway
        ports:
        - containerPort: 9091
