apiVersion: v1
kind: Service
metadata:
  labels:
    app: pushgateway
    release: prometheus-bind5g-vicomtech
  name: pushgateway
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: metrics 
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    app: pushgateway
