apiVersion: v1
kind: Service
metadata:
  name: zoo1
  labels:
    app: zookeeper-1
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: leader
    port: 2181
    targetPort: 2181
    protocol: TCP
  selector:
    app: zookeeper-1
