apiVersion: v1
kind: Service
metadata:
  labels:
    app: mlmodel
  name: mlmodel-service
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mlmodel